apiVersion: v1
kind: Service
metadata:
  name: konga
  labels:
    app.kubernetes.io/name: konga
    helm.sh/chart: konga
    app.kubernetes.io/instance: konga
    app.kubernetes.io/managed-by: konga
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: konga
    app.kubernetes.io/instance: konga
